name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build nodejs
      run: docker build -t aimvector/nodejs:1.0.0 ./test
